blank_issues_enabled: false
contact_links:
  - name: horizOn Documentation
    url: https://horizon.pm
    about: Visit the horizOn website for documentation and guides
  - name: Existing Issues
    url: https://github.com/ProjectMakersDE/horizOn-Changelog/issues
    about: Search open and closed issues before you open a new one
